site_name: Babelbetes

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          heading_level: 2
          show_root_heading: true
          show_root_toc_entry: true
          show_root_full_path: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
 
nav:
 - Babelbetes: index.md
 - How to Guides: how-to-guides.md
 - Code Reference: reference.md
 - Explanation: explanation.md
 - Data Sets: 
    - IOBP2: data_sets/IOBP2-dataset.md
