site_name: Babelbetes

theme: material

markdown_extensions:
  - pymdownx.snippets:
      base_path: ["."]  # Relative to the current Markdown file
  - admonition

extra_css:
  - style.css

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: false
          heading_level: 3
          show_root_heading: true
          show_root_full_path: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_submodules: true
          
nav:
 - Babelbetes: README.md
 - Supported Datasets:
    - IOBP2: data_sets/IOBP2.md
    - DCLP3: data_sets/DCLP3.md
    - DCLP5: data_sets/DCLP5.md
    - PEDAP: data_sets/PEDAP.md
    - FLAIR: data_sets/FLAIR.md
    - LOOP: data_sets/LOOP.md
    - T1DExi: data_sets/T1DEXI.md
    - T1DEXIP: data_sets/T1DEXIP.md
    - Replace BG: data_sets/REPLACE_BG.md
 - Better Datasets: recommendations.md
 - Toolbox Guide:
    - Code Reference: reference.md
    - Study Checklist: checklist.md
    - Best Pracitces: best-practices.md
    - Virtual Environments: python-setup.md
 - Contribute: contribute.md
 - About: about.md
 - License: license.md