site_name: Bebelbetes

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          heading_level: 2
          show_root_heading: true
          show_root_toc_entry: true
          show_root_full_path: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
 
nav:
 - Bebelbetes: index.md
 - How to Guides: how-to-guides.md
 - Code Reference: reference.md
 - Exaplanation: explanation.md