name: Test Code

on:
  push:
    branches:
      - develop
  pull_request: 
    branches: 
      - develop
jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.0'  # Use the Python version compatible with MkDocs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      
      - name: Run tests
        run: |
          python test.py
      
      - name: Build docs
        run: |
          mkdocs build
      
      - name: Deploy docs
        run: |
          pip install mike
          git fetch origin gh-pages --depth=1
          git config user.name docs-bot
          git config user.email docs-bot@users.noreply.github.com
          mike deploy develop --push